// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYbPbPgJQ_2XeJBfkt3HqmJStMPpvbBE',
    appId: '1:966724494324:web:d8dd3219bd30075f124fa1',
    messagingSenderId: '966724494324',
    projectId: 'getd88s74dzbyvweuc5nio1u3fyjuc',
    authDomain: 'getd88s74dzbyvweuc5nio1u3fyjuc.firebaseapp.com',
    storageBucket: 'getd88s74dzbyvweuc5nio1u3fyjuc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGmX6NPnvk4WmNpOf66gjnj147Ko57LM',
    appId: '1:966724494324:android:bda9d8e7f856aa90124fa1',
    messagingSenderId: '966724494324',
    projectId: 'getd88s74dzbyvweuc5nio1u3fyjuc',
    storageBucket: 'getd88s74dzbyvweuc5nio1u3fyjuc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALee3IvFypdHrkS68VD3LQAc0Xn4peog4',
    appId: '1:966724494324:ios:05abe1838dd25027124fa1',
    messagingSenderId: '966724494324',
    projectId: 'getd88s74dzbyvweuc5nio1u3fyjuc',
    storageBucket: 'getd88s74dzbyvweuc5nio1u3fyjuc.firebasestorage.app',
    iosBundleId: 'com.dreamAI.dreamAI',
  );
}
